// I know that's weird to mix ESM and CJS but it works with ncc :)

const core = require('@actions/core')
import fetch from 'node-fetch'

async function main() {
  const url = core.getInput('discord_webhook_url')
  const title = core.getInput('title')
  const message = core.getInput('message')

  const description = `${message}

  [View on GitHub](${process.env.GITHUB_SERVER_URL}/${process.env.GITHUB_REPOSITORY}/actions/runs/${process.env.GITHUB_RUN_ID})
  Generated by [notify-action](https://github.com/neolitec/notify-action)`

  console.log({ title, message })

  const response = await fetch(url, {
    method: 'POST',
    headers: { 'Content-Type': 'application/json' },
    body: JSON.stringify({
      embeds: [{
        color: 0x0099ff,
        title,
        description,
      }],
    })
  })

  if (response.status !== 204) {
    throw new Error(`Discord responded with ${response.status}`)
  }
}

main().then(() => {
  console.log('Successfully called the webhook')
  core.setOutput('result', 'success')
}).catch((err) => {
  console.log('Error while calling the webhook', err)
  core.setFailed(err.message)
  core.setOutput('result', `error: ${err.message}`)
})
